ALTER TABLE "UserLion" ADD COLUMN "bondXp" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "UserLion" ADD COLUMN "bondLevel" INTEGER NOT NULL DEFAULT 1;
ALTER TABLE "UserLion" ADD COLUMN "lastFedAt" DATETIME;
ALTER TABLE "UserLion" ADD COLUMN "lastGroomedAt" DATETIME;
ALTER TABLE "UserLion" ADD COLUMN "lastBondedAt" DATETIME;
